# Generated by Django 5.0.2 on 2024-02-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_partida_statuspartida_time_aposta_partida_time1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bolao.statuspartida'),
            preserve_default=False,
        ),
    ]
