# Generated by Django 5.0.2 on 2024-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_alter_partida_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='gols1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
