# Generated by Django 5.0.2 on 2024-02-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_alter_partida_gols1_alter_partida_gols2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='match',
            new_name='partida',
        ),
    ]
