# Generated by Django 4.2.10 on 2024-02-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_campeonato_statusbolao_alter_aposta_user_bolao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='data_partida',
            field=models.DateField(default='2024-02-13'),
            preserve_default=False,
        ),
    ]
